### ISSUE TITLE
Remove generated files

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-eo-ru#1]
@vyhuholl, these files/folders are generated during build and must not be in the repo:
INSTALL
Makefile
Makefile.in
aclocal.m4
ap_include.am
config.log
config.status
configure
*.bin
install-sh
missing

Please wipe them and remove them from history - as in, rewrite history so that these files never existed in the repo. Since you've done the last commit, you can `git reset` to the commit before your and redo with only the non-generated files, then `git push -f` to rewrite history.

**Comment by vyhuholl** [comment]
done

**Comment by TinoDidriksen** [comment]
Same as -epo...not done. Same problems. Removed Makefile.am and added .DS_Store.
Don't just remove the files and commit again. Entirely undo your commits that added the files and rewrite history.

**Comment by TinoDidriksen** [comment]
It is not enough to just commit changes. The old commits should have been removed.

I've now done it correctly by rewriting history - clone it fresh, and don't blindly commit all files in the future.

Please read up on which files are needed and which are not, and individually add files.
